# Setup
title:               Charlotte's Web
tagline:             'Everything pragmatic and emotional'
description:         Everything I feel like sharing with general public. 
url:                 http://Charlotte-Vert.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Charlotte-Vert
  url:               
  email:             

plugins: 
  - jekyll-paginate
  - jekyll-archives


